### ISSUE TITLE
Cool but could be better. 

### ISSUE THREAD

**Issue by AnimeGeek01** [mn6/nook#11]
**Describe the solution you'd like**
It's nice to see that someone has continued from where animal Crossing Music left off. but there are a few of K.K's new songs from new leaf missing, and the rainy Day theme from Population growing just wanted to point that out i could share them with you if you want. 

**Describe alternatives you've considered**
Also is there a town tune section like Animal Crossing Music if not i think you should add that too.

**Comment by mn6** [comment]
Hi there, I've added New Leaf K.K. songs in the next release. I don't plan on adding Rainy Day just because it would break the flow of how Nook currently works. Since it's just one song rather than different versions of every hourly song, it's awkward to implement. As for the town tune functionality, I don't plan on adding it for the moment. Thanks for your suggestions!
